/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardOrganizationsRouteImport } from './routes/dashboard/organizations/route'
import { Route as DashboardProfileIndexImport } from './routes/dashboard/profile/index'
import { Route as DashboardPersonalprojectsIndexImport } from './routes/dashboard/personal_projects/index'
import { Route as DashboardOverviewIndexImport } from './routes/dashboard/overview/index'
import { Route as DashboardNotificationsIndexImport } from './routes/dashboard/notifications/index'
import { Route as AuthSignupIndexImport } from './routes/auth/signup/index'
import { Route as AuthResetPasswordIndexImport } from './routes/auth/reset-password/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthForgotPasswordIndexImport } from './routes/auth/forgot-password/index'
import { Route as DashboardPersonalprojectsProjectidImport } from './routes/dashboard/personal_projects/$project_id'
import { Route as DashboardOrganizationsOtherorganizationsIndexImport } from './routes/dashboard/organizations/other_organizations/index'
import { Route as DashboardOrganizationsMyorganizationsIndexImport } from './routes/dashboard/organizations/my_organizations/index'
import { Route as DashboardOrganizationsInvitationsIndexImport } from './routes/dashboard/organizations/invitations/index'
import { Route as DashboardOrganizationsInvitationsInvitationidImport } from './routes/dashboard/organizations/invitations/$invitation_id'
import { Route as DashboardOrganizationsTeamsTeamidIndexImport } from './routes/dashboard/organizations/teams/$team_id/index'
import { Route as DashboardOrganizationsOtherorganizationsOrganizationidIndexImport } from './routes/dashboard/organizations/other_organizations/$organization_id/index'
import { Route as DashboardOrganizationsMyorganizationsOrganizationidIndexImport } from './routes/dashboard/organizations/my_organizations/$organization_id/index'
import { Route as DashboardOrganizationsTeamsTeamidMemberidImport } from './routes/dashboard/organizations/teams/$team_id/$member_id'
import { Route as DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsImport } from './routes/dashboard/organizations/my_organizations/$organization_id/sent_invitations'
import { Route as DashboardOrganizationsTeamsTeamidTasksIndexImport } from './routes/dashboard/organizations/teams/$team_id/tasks/index'
import { Route as DashboardOrganizationsTeamsTeamidSubmissionsIndexImport } from './routes/dashboard/organizations/teams/$team_id/submissions/index'
import { Route as DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexImport } from './routes/dashboard/organizations/other_organizations/$organization_id/members/index'
import { Route as DashboardOrganizationsMyorganizationsOrganizationidMembersIndexImport } from './routes/dashboard/organizations/my_organizations/$organization_id/members/index'
import { Route as DashboardOrganizationsTeamsTeamidTasksAssignedtasksImport } from './routes/dashboard/organizations/teams/$team_id/tasks/assigned_tasks'
import { Route as DashboardOrganizationsTeamsTeamidTasksTaskidImport } from './routes/dashboard/organizations/teams/$team_id/tasks/$task_id'
import { Route as DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidImport } from './routes/dashboard/organizations/teams/$team_id/submissions/$submission_id'
import { Route as DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidImport } from './routes/dashboard/organizations/other_organizations/$organization_id/members/$member_id'
import { Route as DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidImport } from './routes/dashboard/organizations/my_organizations/$organization_id/members/$member_id'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardOrganizationsRouteRoute =
  DashboardOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardProfileIndexRoute = DashboardProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardPersonalprojectsIndexRoute =
  DashboardPersonalprojectsIndexImport.update({
    id: '/personal_projects/',
    path: '/personal_projects/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardOverviewIndexRoute = DashboardOverviewIndexImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const AuthSignupIndexRoute = AuthSignupIndexImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthResetPasswordIndexRoute = AuthResetPasswordIndexImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const DashboardPersonalprojectsProjectidRoute =
  DashboardPersonalprojectsProjectidImport.update({
    id: '/personal_projects/$project_id',
    path: '/personal_projects/$project_id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardOrganizationsOtherorganizationsIndexRoute =
  DashboardOrganizationsOtherorganizationsIndexImport.update({
    id: '/other_organizations/',
    path: '/other_organizations/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsMyorganizationsIndexRoute =
  DashboardOrganizationsMyorganizationsIndexImport.update({
    id: '/my_organizations/',
    path: '/my_organizations/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsInvitationsIndexRoute =
  DashboardOrganizationsInvitationsIndexImport.update({
    id: '/invitations/',
    path: '/invitations/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsInvitationsInvitationidRoute =
  DashboardOrganizationsInvitationsInvitationidImport.update({
    id: '/invitations/$invitation_id',
    path: '/invitations/$invitation_id',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsTeamsTeamidIndexRoute =
  DashboardOrganizationsTeamsTeamidIndexImport.update({
    id: '/teams/$team_id/',
    path: '/teams/$team_id/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsOtherorganizationsOrganizationidIndexRoute =
  DashboardOrganizationsOtherorganizationsOrganizationidIndexImport.update({
    id: '/other_organizations/$organization_id/',
    path: '/other_organizations/$organization_id/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsMyorganizationsOrganizationidIndexRoute =
  DashboardOrganizationsMyorganizationsOrganizationidIndexImport.update({
    id: '/my_organizations/$organization_id/',
    path: '/my_organizations/$organization_id/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsTeamsTeamidMemberidRoute =
  DashboardOrganizationsTeamsTeamidMemberidImport.update({
    id: '/teams/$team_id/$member_id',
    path: '/teams/$team_id/$member_id',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsRoute =
  DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsImport.update(
    {
      id: '/my_organizations/$organization_id/sent_invitations',
      path: '/my_organizations/$organization_id/sent_invitations',
      getParentRoute: () => DashboardOrganizationsRouteRoute,
    } as any,
  )

const DashboardOrganizationsTeamsTeamidTasksIndexRoute =
  DashboardOrganizationsTeamsTeamidTasksIndexImport.update({
    id: '/teams/$team_id/tasks/',
    path: '/teams/$team_id/tasks/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsTeamsTeamidSubmissionsIndexRoute =
  DashboardOrganizationsTeamsTeamidSubmissionsIndexImport.update({
    id: '/teams/$team_id/submissions/',
    path: '/teams/$team_id/submissions/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexRoute =
  DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexImport.update(
    {
      id: '/other_organizations/$organization_id/members/',
      path: '/other_organizations/$organization_id/members/',
      getParentRoute: () => DashboardOrganizationsRouteRoute,
    } as any,
  )

const DashboardOrganizationsMyorganizationsOrganizationidMembersIndexRoute =
  DashboardOrganizationsMyorganizationsOrganizationidMembersIndexImport.update({
    id: '/my_organizations/$organization_id/members/',
    path: '/my_organizations/$organization_id/members/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsTeamsTeamidTasksAssignedtasksRoute =
  DashboardOrganizationsTeamsTeamidTasksAssignedtasksImport.update({
    id: '/teams/$team_id/tasks/assigned_tasks',
    path: '/teams/$team_id/tasks/assigned_tasks',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsTeamsTeamidTasksTaskidRoute =
  DashboardOrganizationsTeamsTeamidTasksTaskidImport.update({
    id: '/teams/$team_id/tasks/$task_id',
    path: '/teams/$team_id/tasks/$task_id',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidRoute =
  DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidImport.update({
    id: '/teams/$team_id/submissions/$submission_id',
    path: '/teams/$team_id/submissions/$submission_id',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidRoute =
  DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidImport.update(
    {
      id: '/other_organizations/$organization_id/members/$member_id',
      path: '/other_organizations/$organization_id/members/$member_id',
      getParentRoute: () => DashboardOrganizationsRouteRoute,
    } as any,
  )

const DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidRoute =
  DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidImport.update(
    {
      id: '/my_organizations/$organization_id/members/$member_id',
      path: '/my_organizations/$organization_id/members/$member_id',
      getParentRoute: () => DashboardOrganizationsRouteRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/organizations': {
      id: '/dashboard/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/personal_projects/$project_id': {
      id: '/dashboard/personal_projects/$project_id'
      path: '/personal_projects/$project_id'
      fullPath: '/dashboard/personal_projects/$project_id'
      preLoaderRoute: typeof DashboardPersonalprojectsProjectidImport
      parentRoute: typeof DashboardRouteImport
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/dashboard/notifications/': {
      id: '/dashboard/notifications/'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/overview/': {
      id: '/dashboard/overview/'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/personal_projects/': {
      id: '/dashboard/personal_projects/'
      path: '/personal_projects'
      fullPath: '/dashboard/personal_projects'
      preLoaderRoute: typeof DashboardPersonalprojectsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/organizations/invitations/$invitation_id': {
      id: '/dashboard/organizations/invitations/$invitation_id'
      path: '/invitations/$invitation_id'
      fullPath: '/dashboard/organizations/invitations/$invitation_id'
      preLoaderRoute: typeof DashboardOrganizationsInvitationsInvitationidImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/invitations/': {
      id: '/dashboard/organizations/invitations/'
      path: '/invitations'
      fullPath: '/dashboard/organizations/invitations'
      preLoaderRoute: typeof DashboardOrganizationsInvitationsIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/my_organizations/': {
      id: '/dashboard/organizations/my_organizations/'
      path: '/my_organizations'
      fullPath: '/dashboard/organizations/my_organizations'
      preLoaderRoute: typeof DashboardOrganizationsMyorganizationsIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/other_organizations/': {
      id: '/dashboard/organizations/other_organizations/'
      path: '/other_organizations'
      fullPath: '/dashboard/organizations/other_organizations'
      preLoaderRoute: typeof DashboardOrganizationsOtherorganizationsIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/my_organizations/$organization_id/sent_invitations': {
      id: '/dashboard/organizations/my_organizations/$organization_id/sent_invitations'
      path: '/my_organizations/$organization_id/sent_invitations'
      fullPath: '/dashboard/organizations/my_organizations/$organization_id/sent_invitations'
      preLoaderRoute: typeof DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/teams/$team_id/$member_id': {
      id: '/dashboard/organizations/teams/$team_id/$member_id'
      path: '/teams/$team_id/$member_id'
      fullPath: '/dashboard/organizations/teams/$team_id/$member_id'
      preLoaderRoute: typeof DashboardOrganizationsTeamsTeamidMemberidImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/my_organizations/$organization_id/': {
      id: '/dashboard/organizations/my_organizations/$organization_id/'
      path: '/my_organizations/$organization_id'
      fullPath: '/dashboard/organizations/my_organizations/$organization_id'
      preLoaderRoute: typeof DashboardOrganizationsMyorganizationsOrganizationidIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/other_organizations/$organization_id/': {
      id: '/dashboard/organizations/other_organizations/$organization_id/'
      path: '/other_organizations/$organization_id'
      fullPath: '/dashboard/organizations/other_organizations/$organization_id'
      preLoaderRoute: typeof DashboardOrganizationsOtherorganizationsOrganizationidIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/teams/$team_id/': {
      id: '/dashboard/organizations/teams/$team_id/'
      path: '/teams/$team_id'
      fullPath: '/dashboard/organizations/teams/$team_id'
      preLoaderRoute: typeof DashboardOrganizationsTeamsTeamidIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/my_organizations/$organization_id/members/$member_id': {
      id: '/dashboard/organizations/my_organizations/$organization_id/members/$member_id'
      path: '/my_organizations/$organization_id/members/$member_id'
      fullPath: '/dashboard/organizations/my_organizations/$organization_id/members/$member_id'
      preLoaderRoute: typeof DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/other_organizations/$organization_id/members/$member_id': {
      id: '/dashboard/organizations/other_organizations/$organization_id/members/$member_id'
      path: '/other_organizations/$organization_id/members/$member_id'
      fullPath: '/dashboard/organizations/other_organizations/$organization_id/members/$member_id'
      preLoaderRoute: typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/teams/$team_id/submissions/$submission_id': {
      id: '/dashboard/organizations/teams/$team_id/submissions/$submission_id'
      path: '/teams/$team_id/submissions/$submission_id'
      fullPath: '/dashboard/organizations/teams/$team_id/submissions/$submission_id'
      preLoaderRoute: typeof DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/teams/$team_id/tasks/$task_id': {
      id: '/dashboard/organizations/teams/$team_id/tasks/$task_id'
      path: '/teams/$team_id/tasks/$task_id'
      fullPath: '/dashboard/organizations/teams/$team_id/tasks/$task_id'
      preLoaderRoute: typeof DashboardOrganizationsTeamsTeamidTasksTaskidImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/teams/$team_id/tasks/assigned_tasks': {
      id: '/dashboard/organizations/teams/$team_id/tasks/assigned_tasks'
      path: '/teams/$team_id/tasks/assigned_tasks'
      fullPath: '/dashboard/organizations/teams/$team_id/tasks/assigned_tasks'
      preLoaderRoute: typeof DashboardOrganizationsTeamsTeamidTasksAssignedtasksImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/my_organizations/$organization_id/members/': {
      id: '/dashboard/organizations/my_organizations/$organization_id/members/'
      path: '/my_organizations/$organization_id/members'
      fullPath: '/dashboard/organizations/my_organizations/$organization_id/members'
      preLoaderRoute: typeof DashboardOrganizationsMyorganizationsOrganizationidMembersIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/other_organizations/$organization_id/members/': {
      id: '/dashboard/organizations/other_organizations/$organization_id/members/'
      path: '/other_organizations/$organization_id/members'
      fullPath: '/dashboard/organizations/other_organizations/$organization_id/members'
      preLoaderRoute: typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/teams/$team_id/submissions/': {
      id: '/dashboard/organizations/teams/$team_id/submissions/'
      path: '/teams/$team_id/submissions'
      fullPath: '/dashboard/organizations/teams/$team_id/submissions'
      preLoaderRoute: typeof DashboardOrganizationsTeamsTeamidSubmissionsIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/teams/$team_id/tasks/': {
      id: '/dashboard/organizations/teams/$team_id/tasks/'
      path: '/teams/$team_id/tasks'
      fullPath: '/dashboard/organizations/teams/$team_id/tasks'
      preLoaderRoute: typeof DashboardOrganizationsTeamsTeamidTasksIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardOrganizationsRouteRouteChildren {
  DashboardOrganizationsInvitationsInvitationidRoute: typeof DashboardOrganizationsInvitationsInvitationidRoute
  DashboardOrganizationsInvitationsIndexRoute: typeof DashboardOrganizationsInvitationsIndexRoute
  DashboardOrganizationsMyorganizationsIndexRoute: typeof DashboardOrganizationsMyorganizationsIndexRoute
  DashboardOrganizationsOtherorganizationsIndexRoute: typeof DashboardOrganizationsOtherorganizationsIndexRoute
  DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsRoute: typeof DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsRoute
  DashboardOrganizationsTeamsTeamidMemberidRoute: typeof DashboardOrganizationsTeamsTeamidMemberidRoute
  DashboardOrganizationsMyorganizationsOrganizationidIndexRoute: typeof DashboardOrganizationsMyorganizationsOrganizationidIndexRoute
  DashboardOrganizationsOtherorganizationsOrganizationidIndexRoute: typeof DashboardOrganizationsOtherorganizationsOrganizationidIndexRoute
  DashboardOrganizationsTeamsTeamidIndexRoute: typeof DashboardOrganizationsTeamsTeamidIndexRoute
  DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidRoute: typeof DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidRoute
  DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidRoute: typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidRoute
  DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidRoute: typeof DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidRoute
  DashboardOrganizationsTeamsTeamidTasksTaskidRoute: typeof DashboardOrganizationsTeamsTeamidTasksTaskidRoute
  DashboardOrganizationsTeamsTeamidTasksAssignedtasksRoute: typeof DashboardOrganizationsTeamsTeamidTasksAssignedtasksRoute
  DashboardOrganizationsMyorganizationsOrganizationidMembersIndexRoute: typeof DashboardOrganizationsMyorganizationsOrganizationidMembersIndexRoute
  DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexRoute: typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexRoute
  DashboardOrganizationsTeamsTeamidSubmissionsIndexRoute: typeof DashboardOrganizationsTeamsTeamidSubmissionsIndexRoute
  DashboardOrganizationsTeamsTeamidTasksIndexRoute: typeof DashboardOrganizationsTeamsTeamidTasksIndexRoute
}

const DashboardOrganizationsRouteRouteChildren: DashboardOrganizationsRouteRouteChildren =
  {
    DashboardOrganizationsInvitationsInvitationidRoute:
      DashboardOrganizationsInvitationsInvitationidRoute,
    DashboardOrganizationsInvitationsIndexRoute:
      DashboardOrganizationsInvitationsIndexRoute,
    DashboardOrganizationsMyorganizationsIndexRoute:
      DashboardOrganizationsMyorganizationsIndexRoute,
    DashboardOrganizationsOtherorganizationsIndexRoute:
      DashboardOrganizationsOtherorganizationsIndexRoute,
    DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsRoute:
      DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsRoute,
    DashboardOrganizationsTeamsTeamidMemberidRoute:
      DashboardOrganizationsTeamsTeamidMemberidRoute,
    DashboardOrganizationsMyorganizationsOrganizationidIndexRoute:
      DashboardOrganizationsMyorganizationsOrganizationidIndexRoute,
    DashboardOrganizationsOtherorganizationsOrganizationidIndexRoute:
      DashboardOrganizationsOtherorganizationsOrganizationidIndexRoute,
    DashboardOrganizationsTeamsTeamidIndexRoute:
      DashboardOrganizationsTeamsTeamidIndexRoute,
    DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidRoute:
      DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidRoute,
    DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidRoute:
      DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidRoute,
    DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidRoute:
      DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidRoute,
    DashboardOrganizationsTeamsTeamidTasksTaskidRoute:
      DashboardOrganizationsTeamsTeamidTasksTaskidRoute,
    DashboardOrganizationsTeamsTeamidTasksAssignedtasksRoute:
      DashboardOrganizationsTeamsTeamidTasksAssignedtasksRoute,
    DashboardOrganizationsMyorganizationsOrganizationidMembersIndexRoute:
      DashboardOrganizationsMyorganizationsOrganizationidMembersIndexRoute,
    DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexRoute:
      DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexRoute,
    DashboardOrganizationsTeamsTeamidSubmissionsIndexRoute:
      DashboardOrganizationsTeamsTeamidSubmissionsIndexRoute,
    DashboardOrganizationsTeamsTeamidTasksIndexRoute:
      DashboardOrganizationsTeamsTeamidTasksIndexRoute,
  }

const DashboardOrganizationsRouteRouteWithChildren =
  DashboardOrganizationsRouteRoute._addFileChildren(
    DashboardOrganizationsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardOrganizationsRouteRoute: typeof DashboardOrganizationsRouteRouteWithChildren
  DashboardPersonalprojectsProjectidRoute: typeof DashboardPersonalprojectsProjectidRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  DashboardOverviewIndexRoute: typeof DashboardOverviewIndexRoute
  DashboardPersonalprojectsIndexRoute: typeof DashboardPersonalprojectsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardOrganizationsRouteRoute:
    DashboardOrganizationsRouteRouteWithChildren,
  DashboardPersonalprojectsProjectidRoute:
    DashboardPersonalprojectsProjectidRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  DashboardOverviewIndexRoute: DashboardOverviewIndexRoute,
  DashboardPersonalprojectsIndexRoute: DashboardPersonalprojectsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRouteWithChildren
  '/dashboard/personal_projects/$project_id': typeof DashboardPersonalprojectsProjectidRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/overview': typeof DashboardOverviewIndexRoute
  '/dashboard/personal_projects': typeof DashboardPersonalprojectsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/organizations/invitations/$invitation_id': typeof DashboardOrganizationsInvitationsInvitationidRoute
  '/dashboard/organizations/invitations': typeof DashboardOrganizationsInvitationsIndexRoute
  '/dashboard/organizations/my_organizations': typeof DashboardOrganizationsMyorganizationsIndexRoute
  '/dashboard/organizations/other_organizations': typeof DashboardOrganizationsOtherorganizationsIndexRoute
  '/dashboard/organizations/my_organizations/$organization_id/sent_invitations': typeof DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsRoute
  '/dashboard/organizations/teams/$team_id/$member_id': typeof DashboardOrganizationsTeamsTeamidMemberidRoute
  '/dashboard/organizations/my_organizations/$organization_id': typeof DashboardOrganizationsMyorganizationsOrganizationidIndexRoute
  '/dashboard/organizations/other_organizations/$organization_id': typeof DashboardOrganizationsOtherorganizationsOrganizationidIndexRoute
  '/dashboard/organizations/teams/$team_id': typeof DashboardOrganizationsTeamsTeamidIndexRoute
  '/dashboard/organizations/my_organizations/$organization_id/members/$member_id': typeof DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidRoute
  '/dashboard/organizations/other_organizations/$organization_id/members/$member_id': typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidRoute
  '/dashboard/organizations/teams/$team_id/submissions/$submission_id': typeof DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidRoute
  '/dashboard/organizations/teams/$team_id/tasks/$task_id': typeof DashboardOrganizationsTeamsTeamidTasksTaskidRoute
  '/dashboard/organizations/teams/$team_id/tasks/assigned_tasks': typeof DashboardOrganizationsTeamsTeamidTasksAssignedtasksRoute
  '/dashboard/organizations/my_organizations/$organization_id/members': typeof DashboardOrganizationsMyorganizationsOrganizationidMembersIndexRoute
  '/dashboard/organizations/other_organizations/$organization_id/members': typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexRoute
  '/dashboard/organizations/teams/$team_id/submissions': typeof DashboardOrganizationsTeamsTeamidSubmissionsIndexRoute
  '/dashboard/organizations/teams/$team_id/tasks': typeof DashboardOrganizationsTeamsTeamidTasksIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRouteWithChildren
  '/dashboard/personal_projects/$project_id': typeof DashboardPersonalprojectsProjectidRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/overview': typeof DashboardOverviewIndexRoute
  '/dashboard/personal_projects': typeof DashboardPersonalprojectsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/organizations/invitations/$invitation_id': typeof DashboardOrganizationsInvitationsInvitationidRoute
  '/dashboard/organizations/invitations': typeof DashboardOrganizationsInvitationsIndexRoute
  '/dashboard/organizations/my_organizations': typeof DashboardOrganizationsMyorganizationsIndexRoute
  '/dashboard/organizations/other_organizations': typeof DashboardOrganizationsOtherorganizationsIndexRoute
  '/dashboard/organizations/my_organizations/$organization_id/sent_invitations': typeof DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsRoute
  '/dashboard/organizations/teams/$team_id/$member_id': typeof DashboardOrganizationsTeamsTeamidMemberidRoute
  '/dashboard/organizations/my_organizations/$organization_id': typeof DashboardOrganizationsMyorganizationsOrganizationidIndexRoute
  '/dashboard/organizations/other_organizations/$organization_id': typeof DashboardOrganizationsOtherorganizationsOrganizationidIndexRoute
  '/dashboard/organizations/teams/$team_id': typeof DashboardOrganizationsTeamsTeamidIndexRoute
  '/dashboard/organizations/my_organizations/$organization_id/members/$member_id': typeof DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidRoute
  '/dashboard/organizations/other_organizations/$organization_id/members/$member_id': typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidRoute
  '/dashboard/organizations/teams/$team_id/submissions/$submission_id': typeof DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidRoute
  '/dashboard/organizations/teams/$team_id/tasks/$task_id': typeof DashboardOrganizationsTeamsTeamidTasksTaskidRoute
  '/dashboard/organizations/teams/$team_id/tasks/assigned_tasks': typeof DashboardOrganizationsTeamsTeamidTasksAssignedtasksRoute
  '/dashboard/organizations/my_organizations/$organization_id/members': typeof DashboardOrganizationsMyorganizationsOrganizationidMembersIndexRoute
  '/dashboard/organizations/other_organizations/$organization_id/members': typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexRoute
  '/dashboard/organizations/teams/$team_id/submissions': typeof DashboardOrganizationsTeamsTeamidSubmissionsIndexRoute
  '/dashboard/organizations/teams/$team_id/tasks': typeof DashboardOrganizationsTeamsTeamidTasksIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRouteWithChildren
  '/dashboard/personal_projects/$project_id': typeof DashboardPersonalprojectsProjectidRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/overview/': typeof DashboardOverviewIndexRoute
  '/dashboard/personal_projects/': typeof DashboardPersonalprojectsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/organizations/invitations/$invitation_id': typeof DashboardOrganizationsInvitationsInvitationidRoute
  '/dashboard/organizations/invitations/': typeof DashboardOrganizationsInvitationsIndexRoute
  '/dashboard/organizations/my_organizations/': typeof DashboardOrganizationsMyorganizationsIndexRoute
  '/dashboard/organizations/other_organizations/': typeof DashboardOrganizationsOtherorganizationsIndexRoute
  '/dashboard/organizations/my_organizations/$organization_id/sent_invitations': typeof DashboardOrganizationsMyorganizationsOrganizationidSentinvitationsRoute
  '/dashboard/organizations/teams/$team_id/$member_id': typeof DashboardOrganizationsTeamsTeamidMemberidRoute
  '/dashboard/organizations/my_organizations/$organization_id/': typeof DashboardOrganizationsMyorganizationsOrganizationidIndexRoute
  '/dashboard/organizations/other_organizations/$organization_id/': typeof DashboardOrganizationsOtherorganizationsOrganizationidIndexRoute
  '/dashboard/organizations/teams/$team_id/': typeof DashboardOrganizationsTeamsTeamidIndexRoute
  '/dashboard/organizations/my_organizations/$organization_id/members/$member_id': typeof DashboardOrganizationsMyorganizationsOrganizationidMembersMemberidRoute
  '/dashboard/organizations/other_organizations/$organization_id/members/$member_id': typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersMemberidRoute
  '/dashboard/organizations/teams/$team_id/submissions/$submission_id': typeof DashboardOrganizationsTeamsTeamidSubmissionsSubmissionidRoute
  '/dashboard/organizations/teams/$team_id/tasks/$task_id': typeof DashboardOrganizationsTeamsTeamidTasksTaskidRoute
  '/dashboard/organizations/teams/$team_id/tasks/assigned_tasks': typeof DashboardOrganizationsTeamsTeamidTasksAssignedtasksRoute
  '/dashboard/organizations/my_organizations/$organization_id/members/': typeof DashboardOrganizationsMyorganizationsOrganizationidMembersIndexRoute
  '/dashboard/organizations/other_organizations/$organization_id/members/': typeof DashboardOrganizationsOtherorganizationsOrganizationidMembersIndexRoute
  '/dashboard/organizations/teams/$team_id/submissions/': typeof DashboardOrganizationsTeamsTeamidSubmissionsIndexRoute
  '/dashboard/organizations/teams/$team_id/tasks/': typeof DashboardOrganizationsTeamsTeamidTasksIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/dashboard/personal_projects/$project_id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/dashboard/personal_projects'
    | '/dashboard/profile'
    | '/dashboard/organizations/invitations/$invitation_id'
    | '/dashboard/organizations/invitations'
    | '/dashboard/organizations/my_organizations'
    | '/dashboard/organizations/other_organizations'
    | '/dashboard/organizations/my_organizations/$organization_id/sent_invitations'
    | '/dashboard/organizations/teams/$team_id/$member_id'
    | '/dashboard/organizations/my_organizations/$organization_id'
    | '/dashboard/organizations/other_organizations/$organization_id'
    | '/dashboard/organizations/teams/$team_id'
    | '/dashboard/organizations/my_organizations/$organization_id/members/$member_id'
    | '/dashboard/organizations/other_organizations/$organization_id/members/$member_id'
    | '/dashboard/organizations/teams/$team_id/submissions/$submission_id'
    | '/dashboard/organizations/teams/$team_id/tasks/$task_id'
    | '/dashboard/organizations/teams/$team_id/tasks/assigned_tasks'
    | '/dashboard/organizations/my_organizations/$organization_id/members'
    | '/dashboard/organizations/other_organizations/$organization_id/members'
    | '/dashboard/organizations/teams/$team_id/submissions'
    | '/dashboard/organizations/teams/$team_id/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/dashboard/personal_projects/$project_id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/dashboard/personal_projects'
    | '/dashboard/profile'
    | '/dashboard/organizations/invitations/$invitation_id'
    | '/dashboard/organizations/invitations'
    | '/dashboard/organizations/my_organizations'
    | '/dashboard/organizations/other_organizations'
    | '/dashboard/organizations/my_organizations/$organization_id/sent_invitations'
    | '/dashboard/organizations/teams/$team_id/$member_id'
    | '/dashboard/organizations/my_organizations/$organization_id'
    | '/dashboard/organizations/other_organizations/$organization_id'
    | '/dashboard/organizations/teams/$team_id'
    | '/dashboard/organizations/my_organizations/$organization_id/members/$member_id'
    | '/dashboard/organizations/other_organizations/$organization_id/members/$member_id'
    | '/dashboard/organizations/teams/$team_id/submissions/$submission_id'
    | '/dashboard/organizations/teams/$team_id/tasks/$task_id'
    | '/dashboard/organizations/teams/$team_id/tasks/assigned_tasks'
    | '/dashboard/organizations/my_organizations/$organization_id/members'
    | '/dashboard/organizations/other_organizations/$organization_id/members'
    | '/dashboard/organizations/teams/$team_id/submissions'
    | '/dashboard/organizations/teams/$team_id/tasks'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/dashboard/personal_projects/$project_id'
    | '/auth/forgot-password/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/auth/signup/'
    | '/dashboard/notifications/'
    | '/dashboard/overview/'
    | '/dashboard/personal_projects/'
    | '/dashboard/profile/'
    | '/dashboard/organizations/invitations/$invitation_id'
    | '/dashboard/organizations/invitations/'
    | '/dashboard/organizations/my_organizations/'
    | '/dashboard/organizations/other_organizations/'
    | '/dashboard/organizations/my_organizations/$organization_id/sent_invitations'
    | '/dashboard/organizations/teams/$team_id/$member_id'
    | '/dashboard/organizations/my_organizations/$organization_id/'
    | '/dashboard/organizations/other_organizations/$organization_id/'
    | '/dashboard/organizations/teams/$team_id/'
    | '/dashboard/organizations/my_organizations/$organization_id/members/$member_id'
    | '/dashboard/organizations/other_organizations/$organization_id/members/$member_id'
    | '/dashboard/organizations/teams/$team_id/submissions/$submission_id'
    | '/dashboard/organizations/teams/$team_id/tasks/$task_id'
    | '/dashboard/organizations/teams/$team_id/tasks/assigned_tasks'
    | '/dashboard/organizations/my_organizations/$organization_id/members/'
    | '/dashboard/organizations/other_organizations/$organization_id/members/'
    | '/dashboard/organizations/teams/$team_id/submissions/'
    | '/dashboard/organizations/teams/$team_id/tasks/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/forgot-password/",
        "/auth/login/",
        "/auth/reset-password/",
        "/auth/signup/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/organizations",
        "/dashboard/personal_projects/$project_id",
        "/dashboard/notifications/",
        "/dashboard/overview/",
        "/dashboard/personal_projects/",
        "/dashboard/profile/"
      ]
    },
    "/dashboard/organizations": {
      "filePath": "dashboard/organizations/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/organizations/invitations/$invitation_id",
        "/dashboard/organizations/invitations/",
        "/dashboard/organizations/my_organizations/",
        "/dashboard/organizations/other_organizations/",
        "/dashboard/organizations/my_organizations/$organization_id/sent_invitations",
        "/dashboard/organizations/teams/$team_id/$member_id",
        "/dashboard/organizations/my_organizations/$organization_id/",
        "/dashboard/organizations/other_organizations/$organization_id/",
        "/dashboard/organizations/teams/$team_id/",
        "/dashboard/organizations/my_organizations/$organization_id/members/$member_id",
        "/dashboard/organizations/other_organizations/$organization_id/members/$member_id",
        "/dashboard/organizations/teams/$team_id/submissions/$submission_id",
        "/dashboard/organizations/teams/$team_id/tasks/$task_id",
        "/dashboard/organizations/teams/$team_id/tasks/assigned_tasks",
        "/dashboard/organizations/my_organizations/$organization_id/members/",
        "/dashboard/organizations/other_organizations/$organization_id/members/",
        "/dashboard/organizations/teams/$team_id/submissions/",
        "/dashboard/organizations/teams/$team_id/tasks/"
      ]
    },
    "/dashboard/personal_projects/$project_id": {
      "filePath": "dashboard/personal_projects/$project_id.tsx",
      "parent": "/dashboard"
    },
    "/auth/forgot-password/": {
      "filePath": "auth/forgot-password/index.tsx",
      "parent": "/auth"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password/": {
      "filePath": "auth/reset-password/index.tsx",
      "parent": "/auth"
    },
    "/auth/signup/": {
      "filePath": "auth/signup/index.tsx",
      "parent": "/auth"
    },
    "/dashboard/notifications/": {
      "filePath": "dashboard/notifications/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/overview/": {
      "filePath": "dashboard/overview/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/personal_projects/": {
      "filePath": "dashboard/personal_projects/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/profile/": {
      "filePath": "dashboard/profile/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/organizations/invitations/$invitation_id": {
      "filePath": "dashboard/organizations/invitations/$invitation_id.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/invitations/": {
      "filePath": "dashboard/organizations/invitations/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/my_organizations/": {
      "filePath": "dashboard/organizations/my_organizations/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/other_organizations/": {
      "filePath": "dashboard/organizations/other_organizations/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/my_organizations/$organization_id/sent_invitations": {
      "filePath": "dashboard/organizations/my_organizations/$organization_id/sent_invitations.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/teams/$team_id/$member_id": {
      "filePath": "dashboard/organizations/teams/$team_id/$member_id.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/my_organizations/$organization_id/": {
      "filePath": "dashboard/organizations/my_organizations/$organization_id/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/other_organizations/$organization_id/": {
      "filePath": "dashboard/organizations/other_organizations/$organization_id/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/teams/$team_id/": {
      "filePath": "dashboard/organizations/teams/$team_id/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/my_organizations/$organization_id/members/$member_id": {
      "filePath": "dashboard/organizations/my_organizations/$organization_id/members/$member_id.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/other_organizations/$organization_id/members/$member_id": {
      "filePath": "dashboard/organizations/other_organizations/$organization_id/members/$member_id.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/teams/$team_id/submissions/$submission_id": {
      "filePath": "dashboard/organizations/teams/$team_id/submissions/$submission_id.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/teams/$team_id/tasks/$task_id": {
      "filePath": "dashboard/organizations/teams/$team_id/tasks/$task_id.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/teams/$team_id/tasks/assigned_tasks": {
      "filePath": "dashboard/organizations/teams/$team_id/tasks/assigned_tasks.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/my_organizations/$organization_id/members/": {
      "filePath": "dashboard/organizations/my_organizations/$organization_id/members/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/other_organizations/$organization_id/members/": {
      "filePath": "dashboard/organizations/other_organizations/$organization_id/members/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/teams/$team_id/submissions/": {
      "filePath": "dashboard/organizations/teams/$team_id/submissions/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/organizations/teams/$team_id/tasks/": {
      "filePath": "dashboard/organizations/teams/$team_id/tasks/index.tsx",
      "parent": "/dashboard/organizations"
    }
  }
}
ROUTE_MANIFEST_END */
