/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardProfileIndexImport } from './routes/dashboard/profile/index'
import { Route as DashboardPersonalprojectsIndexImport } from './routes/dashboard/personal_projects/index'
import { Route as DashboardOverviewIndexImport } from './routes/dashboard/overview/index'
import { Route as DashboardOrganizationsIndexImport } from './routes/dashboard/organizations/index'
import { Route as AuthSignupIndexImport } from './routes/auth/signup/index'
import { Route as AuthResetPasswordIndexImport } from './routes/auth/reset-password/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthForgotPasswordIndexImport } from './routes/auth/forgot-password/index'
import { Route as DashboardPersonalprojectsProjectidImport } from './routes/dashboard/personal_projects/$project_id'
import { Route as DashboardOrganizationsOrganizationidIndexImport } from './routes/dashboard/organizations/$organization_id/index'
import { Route as DashboardOrganizationsOrganizationidMembersImport } from './routes/dashboard/organizations/$organization_id/members'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardProfileIndexRoute = DashboardProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardPersonalprojectsIndexRoute =
  DashboardPersonalprojectsIndexImport.update({
    id: '/personal_projects/',
    path: '/personal_projects/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardOverviewIndexRoute = DashboardOverviewIndexImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const AuthSignupIndexRoute = AuthSignupIndexImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthResetPasswordIndexRoute = AuthResetPasswordIndexImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const DashboardPersonalprojectsProjectidRoute =
  DashboardPersonalprojectsProjectidImport.update({
    id: '/personal_projects/$project_id',
    path: '/personal_projects/$project_id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationidIndexRoute =
  DashboardOrganizationsOrganizationidIndexImport.update({
    id: '/organizations/$organization_id/',
    path: '/organizations/$organization_id/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationidMembersRoute =
  DashboardOrganizationsOrganizationidMembersImport.update({
    id: '/organizations/$organization_id/members',
    path: '/organizations/$organization_id/members',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/personal_projects/$project_id': {
      id: '/dashboard/personal_projects/$project_id'
      path: '/personal_projects/$project_id'
      fullPath: '/dashboard/personal_projects/$project_id'
      preLoaderRoute: typeof DashboardPersonalprojectsProjectidImport
      parentRoute: typeof DashboardRouteImport
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/dashboard/organizations/': {
      id: '/dashboard/organizations/'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardOrganizationsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/overview/': {
      id: '/dashboard/overview/'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/personal_projects/': {
      id: '/dashboard/personal_projects/'
      path: '/personal_projects'
      fullPath: '/dashboard/personal_projects'
      preLoaderRoute: typeof DashboardPersonalprojectsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/organizations/$organization_id/members': {
      id: '/dashboard/organizations/$organization_id/members'
      path: '/organizations/$organization_id/members'
      fullPath: '/dashboard/organizations/$organization_id/members'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationidMembersImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/organizations/$organization_id/': {
      id: '/dashboard/organizations/$organization_id/'
      path: '/organizations/$organization_id'
      fullPath: '/dashboard/organizations/$organization_id'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationidIndexImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardPersonalprojectsProjectidRoute: typeof DashboardPersonalprojectsProjectidRoute
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
  DashboardOverviewIndexRoute: typeof DashboardOverviewIndexRoute
  DashboardPersonalprojectsIndexRoute: typeof DashboardPersonalprojectsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardOrganizationsOrganizationidMembersRoute: typeof DashboardOrganizationsOrganizationidMembersRoute
  DashboardOrganizationsOrganizationidIndexRoute: typeof DashboardOrganizationsOrganizationidIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardPersonalprojectsProjectidRoute:
    DashboardPersonalprojectsProjectidRoute,
  DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
  DashboardOverviewIndexRoute: DashboardOverviewIndexRoute,
  DashboardPersonalprojectsIndexRoute: DashboardPersonalprojectsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardOrganizationsOrganizationidMembersRoute:
    DashboardOrganizationsOrganizationidMembersRoute,
  DashboardOrganizationsOrganizationidIndexRoute:
    DashboardOrganizationsOrganizationidIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/personal_projects/$project_id': typeof DashboardPersonalprojectsProjectidRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/organizations': typeof DashboardOrganizationsIndexRoute
  '/dashboard/overview': typeof DashboardOverviewIndexRoute
  '/dashboard/personal_projects': typeof DashboardPersonalprojectsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/organizations/$organization_id/members': typeof DashboardOrganizationsOrganizationidMembersRoute
  '/dashboard/organizations/$organization_id': typeof DashboardOrganizationsOrganizationidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/personal_projects/$project_id': typeof DashboardPersonalprojectsProjectidRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/organizations': typeof DashboardOrganizationsIndexRoute
  '/dashboard/overview': typeof DashboardOverviewIndexRoute
  '/dashboard/personal_projects': typeof DashboardPersonalprojectsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/organizations/$organization_id/members': typeof DashboardOrganizationsOrganizationidMembersRoute
  '/dashboard/organizations/$organization_id': typeof DashboardOrganizationsOrganizationidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/personal_projects/$project_id': typeof DashboardPersonalprojectsProjectidRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/overview/': typeof DashboardOverviewIndexRoute
  '/dashboard/personal_projects/': typeof DashboardPersonalprojectsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/organizations/$organization_id/members': typeof DashboardOrganizationsOrganizationidMembersRoute
  '/dashboard/organizations/$organization_id/': typeof DashboardOrganizationsOrganizationidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/personal_projects/$project_id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/dashboard/organizations'
    | '/dashboard/overview'
    | '/dashboard/personal_projects'
    | '/dashboard/profile'
    | '/dashboard/organizations/$organization_id/members'
    | '/dashboard/organizations/$organization_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/personal_projects/$project_id'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/dashboard/organizations'
    | '/dashboard/overview'
    | '/dashboard/personal_projects'
    | '/dashboard/profile'
    | '/dashboard/organizations/$organization_id/members'
    | '/dashboard/organizations/$organization_id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/personal_projects/$project_id'
    | '/auth/forgot-password/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/auth/signup/'
    | '/dashboard/organizations/'
    | '/dashboard/overview/'
    | '/dashboard/personal_projects/'
    | '/dashboard/profile/'
    | '/dashboard/organizations/$organization_id/members'
    | '/dashboard/organizations/$organization_id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/forgot-password/",
        "/auth/login/",
        "/auth/reset-password/",
        "/auth/signup/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/personal_projects/$project_id",
        "/dashboard/organizations/",
        "/dashboard/overview/",
        "/dashboard/personal_projects/",
        "/dashboard/profile/",
        "/dashboard/organizations/$organization_id/members",
        "/dashboard/organizations/$organization_id/"
      ]
    },
    "/dashboard/personal_projects/$project_id": {
      "filePath": "dashboard/personal_projects/$project_id.tsx",
      "parent": "/dashboard"
    },
    "/auth/forgot-password/": {
      "filePath": "auth/forgot-password/index.tsx",
      "parent": "/auth"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password/": {
      "filePath": "auth/reset-password/index.tsx",
      "parent": "/auth"
    },
    "/auth/signup/": {
      "filePath": "auth/signup/index.tsx",
      "parent": "/auth"
    },
    "/dashboard/organizations/": {
      "filePath": "dashboard/organizations/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/overview/": {
      "filePath": "dashboard/overview/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/personal_projects/": {
      "filePath": "dashboard/personal_projects/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/profile/": {
      "filePath": "dashboard/profile/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/organizations/$organization_id/members": {
      "filePath": "dashboard/organizations/$organization_id/members.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/organizations/$organization_id/": {
      "filePath": "dashboard/organizations/$organization_id/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
